### PR TITLE
Implementation Code Analysis

### PR DESCRIPTION
**Pull request by stefanoPrimo**
Finally, I've added some implementations about fixing code analysis errors.
Here's what I've added:

- Command: "Spread Application Area to Fields": Helps you to spread application areas to Page fields (also request pages)

- Code Actions for this rules: AA0008 - AA0005 - AA0137 - AA0139.
For the fixer AA0008 it is a different type of code action, precisely a "Source Fix All". It can be triggered from the command palette ("Source Action...") or adding a setting to vscode that fix this "On Save"

### CODE REVIEW

**Comment by anzwdev** [comment]
Thank you. It looks nice, I will test it and merge.

**Comment by anzwdev** [comment]
Hi

I am still looking at it. CodeActionsProvider looks great as it gets position of the required fix from the al compiler, but I have a few problems with command adding missing application areas. It only detects existing application areas if the value is "All", if it is different, it still adds another entry to the page field. It also checks the object type by looking at the first line of the file, so it does not work if there is a comment above object definition. Whole idea of the command is great, it is something that we really need, I am just not sure if regular expression is the best solution here. I am testing now if it is possible to use SyntaxRewriter class from AL compiler to transform the source code. I would like to create a c# framework that would allow us to add more code transformation actions. If I fail then I will use your regular expression version, If I succeed I will let you know how to use it and maybe you will have more ideas about another great code transformations commands.

**Comment by stefanoPrimo** [comment]
> commands

Hi,
thanks for all. 
Yeah, the command for spreading the application area it generally fit some scenarios. I've implemented this like that because it fit our programming style. 
Let me know if you will succeed in the syntax rewriter class. I've tried it out but for me, it seems to spend too much effort on some simple things that can be resolved via JS.

**Comment by anzwdev** [comment]
I am merging your changes into development branch as I want to do a few experiments with syntax rewriter and a small refactoring before releasing a new version of the extension. Thank you for submitting your code.

**Comment by anzwdev** [comment]
I've replaced your regex based functionality that adds missing application areas with c# solution using syntax tree transformation functions from al compiler libraries. It supports now fields, actions, control add-in and parts. I've also added another command to vscode to be able to run it for all al files in the project. 

I've also split your code actions provider into the provider and separate code fix classes where each one contains code for a single code fix. You can find them in src\canalyzerfixes folder.

**Pull request merged**
