### PR TITLE
"Sort procedures" Code Command

### PR DESCRIPTION
**Pull request by rvanbekkum**
Hi @anzwdev,

In this pull request you will an implementation for a new code command to sort procedures in natural order in an AL object.
The code action "Sort procedures" will appear when you have selected a procedure ('method declaration') and will sort all procedures of the _same_ symbol-kind, in a [natural order](https://stackoverflow.com/questions/2802341/javascript-natural-sort-of-alphanumerical-strings).

Here is an example:

**BEFORE**
SortExample_Before

**AFTER**
SortExample_After

In this example you can see it will only sort procedures of the same symbol-kind.
In this case, I ran the code-command to sort `MethodDeclaration`-symbols in the file.
Because of that, it does not include the event-declaration in the sorting, only sorts the (regular) procedures and leaves the source of the `IntegrationEventDeclaration` where it is.

Concerning the implementation: I have added a new base class `ALBaseSortCodeCommand` (which extends `ALCodeCommand`).
Currently there is one single subclass `ALSortProceduresCodeCommand` which implements the procedure-sort code-action, but I think other code-actions could follow which can then be implemented in their own subclass.
I've moved the `addFields` and `sortSymbols` code-action implementations into their own subfolders in the `codeactions` folder.

Please let me know what you think about this addition, and/or if you have any further comments or suggestions on this pull request.

### CODE REVIEW

**Comment by rvanbekkum** [comment]
Alternatively, it could be implemented as a command available from the command palette, e.g., "AZ AL Dev Tools: Sort Procedure Declarations", which let's you choose which symbol-kinds to sort. Just let me know what you think.

**Comment by anzwdev** [comment]
Looks good, I will test it and merge. Command is also a good idea as it might be faster to invoke it in some cases.

Thank you

**Comment by rvanbekkum** [comment]
I've made an additional change so that the code-action only shows up on selection of the first line of the selection range of a method-declaration. That is, having it show up from each line within each procedure is a bit too much.

(I actually tried to change this earlier with another commit, but reverted it with a force push, although it would have been much cleaner to just add another revert commit)

**Comment by anzwdev** [comment]
I've merged your change into development and master branches and updated the extension in Visual Studio Marketplace. Thank you for this new functionality.

**Pull request merged**
